const trTR = {
  name: "tr-TR",
  global: {
    undo: "Geri Al",
    redo: "İleri Al",
    confirm: "Onayla",
  },
  Popconfirm: {
    positiveText: "Onayla",
    negativeText: "Vazgeç",
  },
  Cascader: {
    placeholder: "Lütfen seçiniz...",
    loading: "Yükleniyor",
    loadingRequiredMessage: (label) =>
      `Lütfen kontrol etmeden önce ${label}'ın tüm alt öğelerini yükleyin.`,
  },
  Time: {
    dateFormat: "dd/MM/yyyy",
    dateTimeFormat: "dd/MM/yyyy HH:mm:ss",
  },
  DatePicker: {
    yearFormat: "yyyy",
    monthFormat: "MMM",
    dayFormat: "eeeeee",
    yearTypeFormat: "yyyy",
    monthTypeFormat: "MM/yyyy",
    dateFormat: "dd/MM/yyyy",
    dateTimeFormat: "dd/MM/yyyy HH:mm:ss",
    quarterFormat: "yyyy-qqq",
    clear: "Temizle",
    now: "Bugün",
    confirm: "Onayla",
    selectTime: "Saat Seçin",
    selectDate: "Tarih Seçin",
    datePlaceholder: "Tarih Seçin",
    datetimePlaceholder: "Tarih ve Saat Seçin",
    monthPlaceholder: "Ay Seçin",
    yearPlaceholder: "Yıl Seçin",
    quarterPlaceholder: "Yılın Çeyreğini Seçin",
    startDatePlaceholder: "Başlangıç Tarihi",
    endDatePlaceholder: "Bitiş Tarihi",
    startDatetimePlaceholder: "Başlangıç Tarih ve Saat",
    endDatetimePlaceholder: "Bitiş Tarih ve Saat",
    startMonthPlaceholder: "Başlangıç Ayı",
    endMonthPlaceholder: "Bitiş Ayı",
    monthBeforeYear: true,
    firstDayOfWeek: 0,
    today: "Bugün",
  },
  DataTable: {
    checkTableAll: "Tümünü seç",
    uncheckTableAll: "Seçimleri temizle",
    confirm: "Onayla",
    clear: "Temizle",
  },
  LegacyTransfer: {
    sourceTitle: "Kaynak",
    targetTitle: "Hedef",
  },
  Transfer: {
    selectAll: "Tümünü seç",
    unselectAll: "Seçimleri temizle",
    clearAll: "Temizle",
    total: (num) => `${num} toplam kayıt`,
    selected: (num) => `${num} kayıt seçildi`,
  },
  Empty: {
    description: "Veri Yok",
  },
  Select: {
    placeholder: "Lütfen seçiniz...",
  },
  TimePicker: {
    placeholder: "Saat Seçin",
    positiveText: "Tamam",
    negativeText: "Vazgeç",
    now: "Şimdi",
  },
  Pagination: {
    goto: "Git",
    selectionSuffix: "sayfa",
  },
  DynamicTags: {
    add: "Ekle",
  },
  Log: {
    loading: "Yükleniyor",
  },
  Input: {
    placeholder: "Lütfen girdi yapın.",
  },
  InputNumber: {
    placeholder: "Lütfen girdi yapın.",
  },
  DynamicInput: {
    create: "Oluştur",
  },
  ThemeEditor: {
    title: "Tema Editörü",
    clearAllVars: "Tüm Değişkenleri Temizle",
    clearSearch: "Aramayı Temizle",
    filterCompName: "Component Adına Göre Filtrele",
    filterVarName: "Değişken Adına Göre Filtrele",
    import: "İçe Aktar",
    export: "Dışa Aktar",
    restore: "Varsayılana Dön",
  },
  Image: {
    tipPrevious: "Önceki resim (←)",
    tipNext: "Sonraki resim (→)",
    tipCounterclockwise: "Saat yönünün tersine döndür",
    tipClockwise: "Saat yönüne döndür",
    tipZoomOut: "Uzaklaştır",
    tipZoomIn: "Yakınlaştır",
    tipClose: "Kapat (Esc)",
    tipOriginalSize: "Orjinal boyuta dön",
  },
}
export default trTR
